keys:
  - &thang age12gt0669qhhsptwsjeqgnx5dctfyhr0mzqcgrl8u3c83gfv00ucksw5yy39
  - &nebula age1gv6vmrm2pdujce08wj62vlxlfnf0jes72ma0whegn967rjn9m3yqhr0f6a

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *thang
          - *nebula
