# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6cd9d4e6-707c-43f9-8e30-2927e6fd4184";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6cd9d4e6-707c-43f9-8e30-2927e6fd4184".device = "/dev/disk/by-uuid/6cd9d4e6-707c-43f9-8e30-2927e6fd4184";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5656-8035";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-f63d4774-dcc7-4f57-b085-7ad9cd683c57"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
